# Generated by Django 4.1.7 on 2023-02-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zanjir', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('til', models.CharField(blank=True, default='uz', max_length=10, null=True)),
                ('tg_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel_url', models.URLField()),
                ('channel_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('tg_id', models.CharField(max_length=20)),
                ('til', models.CharField(blank=True, default='uz', max_length=10, null=True)),
            ],
        ),
    ]
